// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4786.RobotBuilderTest1;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.AnalogPotentiometer;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;
import edu.wpi.first.wpilibj.interfaces.Potentiometer;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.SampleRobot;
import edu.wpi.first.wpilibj.Timer;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static WPI_TalonSRX frontLeft;
    public static WPI_TalonSRX frontRight;
    public static WPI_TalonSRX midLeft;
    public static WPI_TalonSRX midRight;
    public static WPI_TalonSRX backLeft;
    public static WPI_TalonSRX backRight;
    
    public static DifferentialDrive robotDrive;
	public static int aForwardChannel = 0;
	public static int aReverseChannel = 1;
//	public static int bForwardChannel = 2;
//	public static int bReverseChannel = 3;
	public static int compressormodule = 0;
	
	public static AnalogPotentiometer playKnob;
	public static AnalogPotentiometer positionKnob;

	//PID Constants
	public static double ERROR_CONSTANT_LEFT = 0.0;
	public static double ERROR_CONSTANT_RIGHT = 0.0;
	public static double WHEEL_RADIUS = 3.125; //Inches
	public static double WHEEL_SEPARATION = 5.0; //Inches
	
	public enum AutoPosition {
    	A, B, C, D, E
    }
    public enum AutoPlay {
    	ONE, TWO, THREE, FOUR, FIVE, SIX
    }

    public static void init() {
        frontLeft = new WPI_TalonSRX(13);
        frontRight = new WPI_TalonSRX(14);
        midLeft = new WPI_TalonSRX(15);
        midRight = new WPI_TalonSRX(16);
        backLeft = new WPI_TalonSRX(17);
        backRight = new WPI_TalonSRX(18);
        
        positionKnob = new AnalogPotentiometer(0, 5);
        playKnob = new AnalogPotentiometer(1, 6);
    }
}
